### ISSUE TITLE
Error 5027

### ISSUE THREAD

**Issue by MicroWazzle** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#638]
When going to log in it prompts me to login but never shows username or the line to enter my password and if i do go ahead and put in my password if it shows up it just errors to 5027. I've tried the fixes but they don't work at all.

**Comment by rdavydov** [comment]
You don't need to login by entering a password. You need to configure a runner file (`run.py`) and run it.
See https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2#how-to-use

**Comment by rdavydov** [comment]
Oh, it's that error 5027: **"client blocked from this operation"**. I fixed it in my fork: https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2

**Comment by rdavydov** [comment]
> With that fix you get the cookies from your browser, but the autoclaim feature(+50 points) doesn't work if you get the cookies from your browser, you have to let the console generate them. So what to do?

Try the new version :) https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2

**Comment by redscorpionx** [comment]
> Try the new version :) https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2

i have the latest version of the bot and am still getting this error
